### ISSUE TITLE
[Bug]: YAOS Does Not Recognize my Repo

### ISSUE THREAD

**Issue by g33k247** [mahyarmirrashed/yaos#4]
**Describe the bug**
"Unknown error occurred. Please create an issue."

**To Reproduce**

1. Press the YAOS button.
2. See error

**Expected behavior**
YAOS updates remote Git repository seamlessly.

**Screenshots**
<img width="368" alt="image" src="https://github.com/mahyarmirrashed/yaos/assets/8498814/9f7e33b5-1a3b-4bb2-8846-49851d1a20ea">

**Desktop (please complete the following information):**

- OS: [macOS]
- Obsidian version: Sonoma
- YAOS version: 0.6.1.

**Comment by mahyarmirrashed** [comment]
Thank you for creating this issue. Could you please open the Obsidian application, and do ⌥+⌘+I on your Mac? This will open up the debug tools. Please then head into the `Console` tab. There, when the error occurs when you press the button, you should see a dark red box (that's the error message). Can you screenshot that and paste that here?

**Comment by g33k247** [comment]
Yes that worked and helped me troubleshoot a commit issue.

**Comment by mahyarmirrashed** [comment]
Ok, I will close this issue then. If you can, please share the issue and how you troubleshooted it in this ticket so that others can reference it in the future.
