### ISSUE TITLE
[Bug]: Getting `index.lock` error

### ISSUE THREAD

**Issue by a11smiles** [mahyarmirrashed/yaos#6]
**Describe the bug**
Whenever VS Code is open, I get this issue. Keep in mind that VS Code is open on an _entirely different repo_. There is no `index.lock` file in this `.git` folder.

<img width="545" alt="image" src="https://github.com/mahyarmirrashed/yaos/assets/11803530/8b3f3614-bf02-4a4d-a828-2e6379edcbaf">

**To Reproduce**

1. Open VS Code
2. Try to do a Sync

**Expected behavior**
It should sync. 

**Desktop (please complete the following information):**

- OS: Mac
- Obsidian version: 1.4.16
- YAOS version: 0.6.1

**Additional context**
This should not occur. As a developer, I should have the ability to have VS Code open, especially in a different repo, and still be able to sync my Obsidian. Additionally, why require xtools commandline? Why not just run git from Homebrew? As it stands, this plugin is essentially unusable for anyone doing more than _just_ Obsidian.

**Comment by mahyarmirrashed** [comment]
I'm able to reproduce this bug on my machine, valid bug. Looking into what may be causing it.

**Comment by mahyarmirrashed** [comment]
Should be fixed with latest `0.6.3` release. Please try it out and I'll close the issue.

**Comment by mahyarmirrashed** [comment]
Closing this as fixed. Please reopen if you are continuing to have any bugs.
